sentry_chassis_controller:
  type: sentry_chassis_controller/SentryChassisController
  cmd_vel_topic: /cmd_vel
  cmd_vel_timeout: 0.25
  enable_dynamic_reconfigure: true
  steer_joints:
  - left_front_pivot_joint
  - right_front_pivot_joint
  - left_back_pivot_joint
  - right_back_pivot_joint
  wheel_joints:
  - left_front_wheel_joint
  - right_front_wheel_joint
  - left_back_wheel_joint
  - right_back_wheel_joint
  geometry:
    wheel_base: 0.362
    track_width: 0.362
    wheel_radius: 0.055
  steer_zero_offsets:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  pid:
    steer:
      front_left:
        p: 7.880252444294682
        i: 0.160729173929626
        d: 0.08297143827516885
        i_clamp_min: -0.4
        i_clamp_max: 0.4
        antiwindup: true
        publish_state: true
      front_right:
        p: 7.880252444294682
        i: 0.160729173929626
        d: 0.08297143827516885
        i_clamp_min: -0.4
        i_clamp_max: 0.4
        antiwindup: true
        publish_state: true
      rear_left:
        p: 7.880252444294682
        i: 0.160729173929626
        d: 0.08297143827516885
        i_clamp_min: -0.4
        i_clamp_max: 0.4
        antiwindup: true
        publish_state: true
      rear_right:
        p: 7.880252444294682
        i: 0.160729173929626
        d: 0.08297143827516885
        i_clamp_min: -0.4
        i_clamp_max: 0.4
        antiwindup: true
        publish_state: true
    wheel:
      front_left:
        p: 0.1820002959628533
        i: 0.5457624494752925
        d: 0.0153523620194787
        i_clamp_min: -2.0
        i_clamp_max: 2.0
        antiwindup: true
        publish_state: true
      front_right:
        p: 0.1820002959628533
        i: 0.5457624494752925
        d: 0.0153523620194787
        i_clamp_min: -2.0
        i_clamp_max: 2.0
        antiwindup: true
        publish_state: true
      rear_left:
        p: 0.1820002959628533
        i: 0.5457624494752925
        d: 0.0153523620194787
        i_clamp_min: -2.0
        i_clamp_max: 2.0
        antiwindup: true
        publish_state: true
      rear_right:
        p: 0.1820002959628533
        i: 0.5457624494752925
        d: 0.0153523620194787
        i_clamp_min: -2.0
        i_clamp_max: 2.0
        antiwindup: true
        publish_state: true
