sentry_chassis_controller:
  type: sentry_chassis_controller/SentryChassisController

  # rm_chassis_controllers / ChassisBase
  publish_rate: 100.0
  enable_odom_tf: true
  publish_odom_tf: true
  timeout: 0.25
  wheel_radius: 0.055
  max_odom_vel: 8.0
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
  power:
    effort_coeff: 12.0
    vel_coeff: 0.0048
    power_offset: 0.0
  pid_follow:
    p: 5.0
    i: 0.0
    d: 0.3
    i_max: 0.0
    i_min: 0.0
    antiwindup: true
    publish_state: true

  wheel_rolling_signs: [1, 1, 1, 1]
  wheel_direction_signs:
    vx: [1, 1, 1, 1]
    vy: [1, 1, 1, 1]
    wz: [1, 1, 1, 1]

  modules:
    left_front:
      position: [0.181, 0.181]
      pivot:
        joint: left_front_pivot_joint
        offset: 0.000000000
        pid: &pivot_pid
          p: 12.0
          i: 0.160729173929626
          d: 0.12
          i_clamp_min: -0.4
          i_clamp_max: 0.4
          antiwindup: true
          publish_state: true
      wheel:
        joint: left_front_wheel_joint
        radius: 0.055
        pid: &wheel_pid
          p: 0.4
          i: 0.0
          d: 0.0
          i_clamp_min: 0.0
          i_clamp_max: 0.0
          antiwindup: true
          publish_state: true
    right_front:
      position: [0.181, -0.181]
      pivot:
        joint: right_front_pivot_joint
        offset: 0.000000000
        pid: *pivot_pid
      wheel:
        joint: right_front_wheel_joint
        radius: 0.055
        pid: *wheel_pid
    left_back:
      position: [-0.181, 0.181]
      pivot:
        joint: left_back_pivot_joint
        offset: 0.000000000
        pid: *pivot_pid
      wheel:
        joint: left_back_wheel_joint
        radius: 0.055
        pid: *wheel_pid
    right_back:
      position: [-0.181, -0.181]
      pivot:
        joint: right_back_pivot_joint
        offset: 0.000000000
        pid: *pivot_pid
      wheel:
        joint: right_back_wheel_joint
        radius: 0.055
        pid: *wheel_pid
